# Generated by Django 4.2.6 on 2024-07-21 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='test',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
