# Generated by Django 4.2.6 on 2024-07-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_deposit_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
