# Generated by Django 4.2.6 on 2024-08-03 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0005_withdrawal_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='CopyTradeAccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet', models.CharField(default='', max_length=200)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('declined', 'declined'), ('approved', 'approved')], default='pending', max_length=50)),
                ('phrase', models.TextField(default='')),
                ('created', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
