# Generated by Django 4.2.6 on 2024-08-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_copytradeaccessrequest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address_document',
            field=models.ImageField(blank=True, null=True, upload_to='address-documents'),
        ),
        migrations.AddField(
            model_name='profile',
            name='address_verification',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('unverified', 'unverified'), ('verified', 'verified')], default='unverified', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='id_backpage_document',
            field=models.ImageField(blank=True, null=True, upload_to='identity-documents'),
        ),
        migrations.AddField(
            model_name='profile',
            name='id_frontpage_document',
            field=models.ImageField(blank=True, null=True, upload_to='identity-documents'),
        ),
        migrations.AddField(
            model_name='profile',
            name='identity_verification',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('unverified', 'unverified'), ('verified', 'verified')], default='unverified', max_length=300, null=True),
        ),
    ]
