# Generated by Django 4.2.6 on 2024-09-02 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_profile_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit_wallets',
            name='image',
        ),
        migrations.RemoveField(
            model_name='deposit_wallets',
            name='ticker_code',
        ),
    ]
